GEOPY-1147
MiraGeoscience/las-geoh5 pull request #13
Opened 2023-11-10 22:13 UTC by benk-mira

Push through GEOPY-1144 first

2023-12-06 19:50 UTC, domfournier approved these changes
Looks good.

2023-12-06 19:50 UTC, domfournier commented on las_geoh5/.idea/.gitignore
Can you add .ideas to the list of ignores?

2023-12-06 22:22 UTC, domfournier approved these changes
Go for tests

2024-01-11 19:24 UTC, domfournier submitted a review, later dismissed
Looks good. Let's finish the geoh5py PR, and update the lock file before merging.

2024-01-12 20:22 UTC, domfournier reviewed
Almost there. See comment.

2024-01-12 20:22 UTC, domfournier commented on pyproject.toml
> -addopts = "--cov las_geoh5 --cov-report html --cov-report term-missing:skip-covered"
Can you bring this back, and remove the `fail_under = 80` below? 
I can show you how to make it pass with pycharm.

2024-01-12 22:57 UTC, domfournier approved these changes
Great. Thanks for the changes.

2024-01-14 16:51 UTC, sebhmg requested changes
retore the .idea files

2024-01-14 16:51 UTC, sebhmg commented on .idea/scopes/sources.xml
restore file: copy the one from python-template repo, and rename my_app to las-geoh5

2024-01-14 16:51 UTC, sebhmg commented on .idea/copyright/profiles_settings.xml
keep this file

2024-01-14 16:51 UTC, sebhmg commented on .idea/copyright/MiraGeoscience.xml
restore file: copy the one from python-template repo, and rename `my_app` to `las-geoh5`

2024-01-17 02:54 UTC, domfournier approved these changes
Looking good. Moving to test

2024-01-17 16:22 UTC, sebhmg commented on .idea/scopes/sources.xml
> +  <scope name="sources" pattern="(file:las-geoh5//*||file:devtools/*||file:tests//*||file:README*.rst)&amp;&amp;!file:*//htmlcov//*&amp;&amp;!file:*//.coverage&amp;&amp;!file:*//.*//*" />
```suggestion
  <scope name="sources" pattern="(file:las_geoh5//*||file:devtools/*||file:tests//*||file:README*.rst)&amp;&amp;!file:*//htmlcov//*&amp;&amp;!file:*//.coverage&amp;&amp;!file:*//.*//*" />
```

2024-01-18 21:26 UTC, domfournier approved these changes
Looks good. Just need to figure out what's wrong with poetry with @sebhmg

2024-01-19 17:06 UTC, sebhmg approved these changes

2024-01-19 18:07 UTC, merged